apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aegisvault-api-hpa
  namespace: aegisvault
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aegisvault-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: aegis_query_latency_p95
        target:
          type: AverageValue
          averageValue: 500m
