"""
POST /query — Fully guarded RAG query endpoint
------------------------------------------------
Passes every request through all 6 security layers
via InferencePipeline.query().

Auth: X-API-Key header (set API_KEYS in .env)
"""

from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field

from aegisVault.app.deps import verify_api_key, limiter

router = APIRouter()


# ── Request / Response schemas ─────────────────────────────────────────

class QueryRequest(BaseModel):
    query:      str             = Field(..., min_length=3, max_length=2000,
                                        description="The user's query text.",
                                        json_schema_extra={"example": "What is our refund policy?"})
    user_id:    str             = Field(..., pattern=r"^[a-zA-Z0-9_\-]{1,64}$",
                                        description="Unique identifier for the user.",
                                        json_schema_extra={"example": "u001"})
    user_roles: List[str]       = Field(default=["employee"],
                                        description="RBAC roles the user holds. Highest clearance dictates context visibility.",
                                        json_schema_extra={"example": ["employee"]})
    tenant_id:  str             = Field(default="default", pattern=r"^[a-zA-Z0-9_\-]{1,64}$",
                                        description="Tenant identifier for logical graph separation.",
                                        json_schema_extra={"example": "acme_corp"})
    top_k:      int             = Field(default=5, ge=1, le=20,
                                        description="Number of context chunks to retrieve.")
    session_id: Optional[str]   = Field(default=None, description="Conversation session ID for memory context.",
                                        json_schema_extra={"example": "sess_001"})

class QueryResponse(BaseModel):
    trace_id:       str         = Field(description="Unique trace ID spanning the entire request lifecycle (matches X-Request-ID).")
    response:       str         = Field(description="The safe, scrubbed response generated by the LLM.")
    chunks_used:    int         = Field(description="Number of document chunks authorized and sent as context.")
    rbac_blocked:   int         = Field(description="Number of document chunks retrieved but blocked by RBAC/tenant filters.")
    pii_redacted:   int         = Field(description="Number of PII entities redacted from the LLM output.")
    canary_leaked:  bool        = Field(description="True if the LLM leaked a canary token.")
    latency_ms:     int         = Field(description="Total latency of the query execution in milliseconds.")


# ── Endpoint ───────────────────────────────────────────────────────────

@router.post("", response_model=QueryResponse)
@limiter.limit("60/minute")
async def run_query(
    req: QueryRequest,
    request: Request,
    _key: str = Depends(verify_api_key),
):
    """
    Run a fully guarded RAG query through all 6 security layers:

    - Layer 2: Semantic router (injection + jailbreak detection)
    - Layer 3: RBAC retrieval filter (sensitivity class + tenant isolation)
    - Layer 4: Clean context construction
    - Layer 5: Output sanitizer (PII scrub + canary check)
    - Layer 6: Privacy-safe audit log
    """
    pipeline = getattr(request.app.state, "inference_pipeline", None)
    if not pipeline:
        raise HTTPException(status_code=503, detail="Inference pipeline not ready")

    # Access trace_id from middleware state
    trace_id = getattr(request.state, "trace_id", None)

    import asyncio
    result = await asyncio.to_thread(
        pipeline.query,
        user_query=req.query.strip(),
        user_id=req.user_id,
        user_roles=req.user_roles,
        tenant_id=req.tenant_id,
        top_k=req.top_k,
        session_id=req.session_id,
        trace_id=trace_id,
    )

    return QueryResponse(
        trace_id=result.trace_id,
        response=result.safe_response,
        chunks_used=result.chunks_used,
        rbac_blocked=result.rbac_blocked,
        pii_redacted=result.pii_redacted,
        canary_leaked=result.canary_leaked,
        latency_ms=result.latency_ms,
    )
